# Generated by Django 5.2.6 on 2025-09-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_count', models.IntegerField()),
                ('success_description', models.CharField(max_length=100)),
            ],
        ),
    ]
