# Generated by Django 5.2.6 on 2025-10-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutwork',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
