# Generated by Django 5.2.6 on 2025-10-01 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_aboutwork_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
